# 
# Home Assistant Automation Blueprint
#
# Automatically turns of heating if door or Windows is open for a specific amount of time 
#
# Rev 2 with three Timers and two Notify Devices
# Modified by Johan Schelin, Mar. 2021

blueprint:
  name: Notification to Close a Window or a Door
  description: Notification to close windows if it is cold outside
  domain: automation
  input:
    contact_sensor:
      name: Contact Sensor
      description: The window or door sensor that triggers the automation.
      selector:
        entity:
          domain: binary_sensor
    first_timer:
      name: First timer
      description: The first notification timer (in minutes).
      default: 60
      selector:
        number:
          min: 1.0
          step: 5.0
          max: 120.0
          mode: slider
    second_timer:
      name: Second timer
      description: The second notification timer (in minutes).
      default: 120
      selector:
        number:
          min: 30.0
          step: 10.0
          max: 240.0
          mode: slider
    third_timer:
      name: Third timer
      description: The first notification timer (in minutes).
      default: 240
      selector:
        number:
          min: 60.0
          step: 30.0
          max: 500.0
          mode: slider
    temperature:
      name: Temperature
      description: The outside temperature below which the notification should be
        sent.
      default: 20
      selector:
        number:
          min: 0.0
          step: 1.0
          max: 25.0
          mode: slider
    temperature_sensor:
      name: Outdoor Temperature Sensor
      description: 'The outdoor temp sensor'
      selector:
        device:
    notification_service:
      name: Notification Platform Service
      selector:
        text:
          type: text
variables:
  var_notification_service: !input notification_service
trigger:
- platform: state
  entity_id: !input 'contact_sensor'
  from: 'off'
  to: 'on'
  for:
    hours: 0
    minutes: !input 'first_timer'
    seconds: 0
- platform: state
  entity_id: !input 'contact_sensor'
  from: 'off'
  to: 'on'
  for:
    hours: 0
    minutes: !input 'second_timer'
    seconds: 0
- platform: state
  entity_id: !input 'contact_sensor'
  from: 'off'
  to: 'on'
  for:
    hours: 0
    minutes: !input 'third_timer'
    seconds: 0
condition:
- condition: state
  entity_id: !input 'contact_sensor'
  state: 'on'
- condition: numeric_state
  entity_id: !input 'temperature_sensor'
  attribute: temperature
  below: !input 'temperature'
action:
  service: notify.{{var_notification_service}}
  data:
    message: Time to close {{trigger.to_state.attributes.friendly_name}}.
    title: Close {{trigger.to_state.attributes.friendly_name}}!
mode: single
